config/routes.rb
Rails.application.routes.draw do
  get '/ultimate', to: "pages#players"

  get 'users/show'
  get 'users/edit', to: "users#edit"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :players do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end
  get "dashboard/bookings/:id", to:"bookings#show", as: "show_new_booking"
  get "dashboard", to: "pages#dashboard"
  patch "dashboard/bookings/:id", to:"bookings#accept", as: "accept_new_booking"
  put "dashboard/bookings/:id", to:"bookings#decline", as: "decline_new_booking"

  resources :bookings do
    resources :messages, only: [:index, :create, :show]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :players
  has_many :messages
  has_many :bookings_as_owner, through: :players, source: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = scope_policy(User)
  end

  def show
    @user = current_user
    authorize @user
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user.update(user_params)
    authorize @user
    redirect_to users_show_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo, :email)
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="container-form">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <h2>Edit profile</h2>
        <%= simple_form_for(@user) do |f| %>

          <% if @user.errors.any? %>
            <div class="errors-container">
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :email %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "Submit changes", class: "btn-yellow-sm btn-margin-top" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p><%= @user.email %></p>
<p><%= @user.first_name %></p>
<p><%= @user.last_name %></p>
<p><%= @user.photo %></p>

<%= link_to 'Edit', users_edit_path %>