config/routes.rb
Rails.application.routes.draw do
  get '/ultimate', to: "pages#players"

  get 'users/show'
  get 'users/edit', to: "users#edit"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :players do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end
  get "dashboard/bookings/:id", to:"bookings#show", as: "show_new_booking"
  get "dashboard", to: "pages#dashboard"
  patch "dashboard/bookings/:id", to:"bookings#accept", as: "accept_new_booking"
  put "dashboard/bookings/:id", to:"bookings#decline", as: "decline_new_booking"

  resources :bookings do
    resources :messages, only: [:index, :create, :show]
  end

end

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="tabs">
      <a class="tab active" href="" id="players-trigger">
        <h3>My players</h3>
      </a>
      <a class="tab" href="" id="bookings-trigger">
        <h3>Bookings</h3>
      </a>
    </div>
    <div id="players">
      <% @players.each do |player| %>
        <div class="message" data-player-id="<%= player.id %>">
          <%= image_tag "#{player.photo}", style:'height:50px;width:50px;border-radius:50%;' %>
          <div class="message-name">
            <h3><%= player.name %></h3>
            <p><%= player.level %></p>
          </div>
          <div class="message-body">
            <p><strong>Description</strong></p>
            <p><%= player.description %></p>
          </div>
          <div class="message-status">
            <%=  link_to edit_player_path(player), class: "btn-option" do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <% if (@all_bookings.select{|booking| booking.player_id == player.id}.blank?) %>
              <%=  link_to player_path(player), class: "btn-option", method: :delete, remote: true do %>
                <i class="fas fa-trash-alt"></i>
              <% end  %>
            <% else %>
                <i class="fas fa-trash-alt hidd btn-option"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div id="bookings" class="hidden">
      <% if @bookings_as_owner.present? %>
        <h4>My players bookings</h4>
        <% @all_bookings.each do |booking| %>
          <% if booking.player.user == current_user %>
            <div class="message">
              <%= image_tag "#{booking.player.photo}", style:'height:50px;width:50px;border-radius:50%;' %>
              <div class="message-name">
                <h3><%= booking.player.name %></h3>
                <p><%= booking.player.level %></p>
              </div>
              <div class="message-body">
                <p><strong>Duration</strong></p>
                <p><%= number_with_delimiter(booking.number_of_days, :delimiter => ',') %> Days </p>
              </div>
              <div class="message-body">
                <p><strong>Dates</strong></p>
                <p> from <%= number_with_delimiter(booking.pick_your_date, :delimiter => ',') %> to <%= number_with_delimiter(booking.end_date, :delimiter => ',')%> </p>
              </div>
              <div class="message-body">
                <p><strong>Total Price</strong></p>
                <p><%= number_with_delimiter(booking.total_price, :delimiter => ',')%> €</p>
              </div>
              <div class="message-body">
                <p><strong>Status</strong></p>
                <% if booking.status == "Accepted" %>
                  <p class="status accepted"><%= booking.status %></p>
                <% elsif booking.status == "Declined" %>
                  <p class="status declined"><%= booking.status %></p>
                <% else %>
                  <p class="status pending"><%= booking.status %></p>
                <% end %>
              </div>
              <div class="message-body">
                <p><strong>Email</strong></p>
                <%= link_to booking_messages_path(booking), class: "btn-option message-body-counter", method: :get do %>
                  <% if booking.messages.count > 0 %>
                    <div class="inbox-counter">
                      <p><%= booking.messages.count %></p>
                    </div>
                  <% end %>
                  <i class="fas fa-envelope"></i>
                <% end %>
              </div>
              <% if booking.status == 'pending' %>
              <div class="message-body">
                <p><strong>Action</strong></p>
                <p><%= link_to 'Accept', accept_new_booking_path(booking), method: :patch %> <%= link_to 'Decline', decline_new_booking_path(booking), method: :put %></p>
              </div>

              <% end %>
            </div>

          <% end %>
        <% end %>
      <% end %>
      <% if @bookings_as_renter.present? %>
      <h4>My bookings</h4>
      <% @bookings.each do |booking| %>
          <div class="message">
            <%= image_tag "#{booking.player.photo}", style:'height:50px;width:50px;border-radius:50%;' %>
            <div class="message-name">
              <h3><%= booking.player.name %></h3>
              <p><%= booking.player.level %></p>
            </div>
            <div class="message-body">
              <p><strong>Duration</strong></p>
              <p><%= number_with_delimiter(booking.number_of_days, :delimiter => ',') %> Days </p>
            </div>
            <div class="message-body">
              <p><strong>Dates</strong></p>
              <p> from <%= number_with_delimiter(booking.pick_your_date, :delimiter => ',') %> to <%= number_with_delimiter(booking.end_date, :delimiter => ',')%> </p>
            </div>
            <div class="message-body">
              <p><strong>Total Price</strong></p>
              <p><%= number_with_delimiter(booking.total_price, :delimiter => ',') %> €</p>
            </div>
            <div class="message-body">
              <p><strong>Status</strong></p>
                <% if booking.status == "Accepted" %>
                  <p class="status accepted"><%= booking.status %></p>
                <% elsif booking.status == "Declined" %>
                  <p class="status declined"><%= booking.status %></p>
                <% else %>
                  <p class="status pending"><%= booking.status %></p>
                <% end %>
            </div>
            <div class="message-body">
              <p><strong>Email</strong></p>
              <%= link_to booking_messages_path(booking), class: "btn-option message-body-counter", method: :get do %>
                <% if booking.messages.count > 0 %>
                  <div class="inbox-counter">
                    <p><%= booking.messages.count %></p>
                  </div>
                <% end %>
                <i class="fas fa-envelope"></i>
              <% end %>
            </div>
          </div>
      <% end %>
    <% end %>

    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,90,146,0.3) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "banner-home.jpg" %>);">
  <div class="banner-content">
    <h1>Rent footbal players from top clubs</h1>
    <p>Find stars ... and goats</p>
    <%= form_tag players_path, method: :get, class: "form-inline form-home" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control input-home",
        placeholder: "Find a goat"
      %>
      <%= button_tag "Goat Search", class: "btn-yellow" %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @players.each do |player|  %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path player.photo %>);">
        <%= link_to player_path(player) do %>
        <div class="card-body">
          <div class="card-category"><%= player.level %></div>
          <div class="card-description">
            <h2><%= player.name %></h2>
            <p><%= player.position %></p>
          </div>
        </div>
        <div class="card-footer">
          <% array = [] %>
          <% player.reviews.each do |review|  %>
            <% array << review.rating %>
          <% end %>
          <% total = array.sum / player.reviews.count.to_f %>

          <% count = 0 %>
          <% 5.times do %>
            <% if total > count %>
              <i class="fas fa-star"></i>
            <% else %>
              <i class="far fa-star"></i>
            <% end %>
            <% count += 1 %>
          <% end %>
          (<%= player.reviews.count %>)

          <p><%= number_with_delimiter(player.price_per_day, :delimiter => ',') %> € per day</p>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/players.html.erb
<div class="container">
  <h1>Best players</h1>
<div class="container-gut" style="background-image:linear-gradient(-225deg, rgba(0,90,146,0.3) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "pitch.jpg" %>);">
  <div class="flex-item goalkeeper">
      <% @gks.each do |gk| %>
        <%= link_to player_path(gk), style: "text-decoration:none;" do %>
        <div class="flex-element">
          <div class="flex-image">
            <%= cl_image_tag gk.photo, style: "border-radius:5px;", size: "80" %>
          </div>
          <div class="flex-list">
          <ul>
            <li><%= gk.name %></li>

            <% count = 0 %>
            <% 5.times do %>
              <% if gk.average_rating > count %>
                <i class="fas fa-star"></i>
              <% else %>
                <i class="far fa-star"></i>
              <% end %>
              <% count += 1 %>
            <% end %></li>
          </ul>
        </div>
        </div>
        <% end %>
      <% end %>
  </div>
  <div class="flex-item">
    <% @backs.each do |back| %>
      <%= link_to player_path(back), style: "text-decoration:none;" do %>
      <div class="flex-element">
        <div class="flex-image">
          <%= cl_image_tag back.photo, style: "border-radius:5px;", size: "80" %>
        </div>
        <div class="flex-list">
          <ul>
            <li><%= back.name %></li>


            <% count = 0 %>
            <% 5.times do %>
              <% if back.average_rating > count %>
                <i class="fas fa-star"></i>
              <% else %>
                <i class="far fa-star"></i>
              <% end %>
              <% count += 1 %>
            <% end %></li>
          </ul>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
  <div class="flex-item">
    <% @midfielders.each do |midfielder| %>
      <%= link_to player_path(midfielder), style: "text-decoration:none;" do %>
        <div class="flex-element">
          <div class="flex-image">
            <%= cl_image_tag midfielder.photo, style: "border-radius:5px;", size: "80" %>
          </div>
          <div class="flex-list">
            <ul>
              <li><%= midfielder.name %></li>

              <% count = 0 %>
              <% 5.times do %>
                <% if midfielder.average_rating > count %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %></li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
    </ul>
  </div>
  <div class="flex-item">
    <% @forwards.each do |forward| %>
      <%= link_to player_path(forward), style: "text-decoration:none;" do %>
        <div class="flex-element">
          <div class="flex-image">
            <%= cl_image_tag forward.photo, style: "border-radius:5px;", size: "80" %>
          </div>
          <div class="flex-list">
            <ul>
              <li><%= forward.name %></li>

              <% count = 0 %>
              <% 5.times do %>
                <% if forward.average_rating > count %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %></li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>